---
title: "NHTS Summarizer - Demo 2"
author: "Alex Cates"
date: "January 2, 2017"
output: html_document
---

```{r, warning=FALSE, message=FALSE}

# load packages
library(data.table)
library(magrittr) # Not required for analysis, but helpful.

# source code
source('make_table.R')
source('make_bar_chart.R')
source('make_html_table.R')
source('util.R')

```


## Reading and Merging the Data
The first step is to read in the data. Due to the size of the csvs, we will read in only necessary columns using
data.table's `fread` function. We will then merge the weights with the survey data using unique identifiers.

```{r, warning=FALSE, message=FALSE}

# There are 100 replicate weight names. Use get_wgt_names to create the vector of names.
wgt_names <- get_wgt_names('DAYWGT')

# Read in the two necessary datasets
per50wt <- fread('./data/2009/per50wt.csv', select = c('HOUSEID','PERSONID',wgt_names))
DAYV2PUB <- fread('./data/2009/DAYV2PUB.csv',select = c('HOUSEID','PERSONID','HH_RACE','HHFAMINC','HBHUR','LIF_CYC','VMT_MILE','HHSTATE'))

# Set the appropriate unique identifiers for merging
setkeyv(per50wt, c('HOUSEID','PERSONID'))
setkeyv(DAYV2PUB, c('HOUSEID','PERSONID'))

# merge the datasets
dt <- DAYV2PUB[per50wt, nomatch=0]

```

#### 1. Average Trip Rate by State.
```{r, warning=FALSE, message=FALSE}

tbl1 <- make_table(
  data = dt, 
  agg = 'avg_trip_rate',
  factors = 'HHSTATE',
  wgt_name = 'DAYWGT'
)

head(tbl1)

```

#### 2. Average Vehicle Miles by State.
```{r, warning=FALSE, message=FALSE}

tbl2 <- make_table(
  data = dt, 
  agg = 'avg',
  agg_var = 'VMT_MILE',
  factors = 'HHSTATE',
  wgt_name = 'DAYWGT',
  subset = 'VMT_MILE >= 0'
)

head(tbl2)

```

