// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Rcpp_wgtavg
double Rcpp_wgtavg(NumericVector x, NumericVector wgts);
RcppExport SEXP _summarizeNHTS_Rcpp_wgtavg(SEXP xSEXP, SEXP wgtsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wgts(wgtsSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_wgtavg(x, wgts));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_wgtsum
double Rcpp_wgtsum(NumericVector x, NumericVector wgts);
RcppExport SEXP _summarizeNHTS_Rcpp_wgtsum(SEXP xSEXP, SEXP wgtsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wgts(wgtsSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_wgtsum(x, wgts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_summarizeNHTS_Rcpp_wgtavg", (DL_FUNC) &_summarizeNHTS_Rcpp_wgtavg, 2},
    {"_summarizeNHTS_Rcpp_wgtsum", (DL_FUNC) &_summarizeNHTS_Rcpp_wgtsum, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_summarizeNHTS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
